### ISSUE TITLE
saving visual output

### ISSUE THREAD

**Issue by eoziolor** [MariaNattestad/dot#1]
Hi, I find the Dot tool very useful for visualizing Mummer output! Thank you for creating this tool!

Is there a way to save the output in a high quality image? Maybe I'm missing it, but it is not obvious to me how I'd do that. Thank you!

-Elias

**Comment by MariaNattestad** [comment]
Hi Elias

I'm glad you have found Dot useful!
Unfortunately, saving a high quality image isn't possible because to make it scalable, I had to layer canvas and svg on top of each other. There are libraries for saving the SVG part, but then the alignments wouldn't be included, so that would not work at all in this case.
The best option is to take a screenshot.

Sorry about that!
Maria

**Comment by eoziolor** [comment]
I appreciate the explanation, Maria. Thanks for a very helpful and easy to use resource!
